title: "Your awesome title"
email: "your-email@example.com"
description: "test"
baseurl: "/sitetest" 
url: "https://lvdesign.github.io/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
